using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;

namespace OrderFlow.Payments.API.Managers.DataContext;

/// <summary>
/// Builds the context for <c>dotnet ef migrations</c>, and for nothing else.
/// </summary>
/// <remarks>
/// The running service gets its connection string from Aspire, which is not available to the EF
/// tooling. This factory hands EF a connection string it never opens: migrations are generated by
/// comparing the model to the previous migration, not by talking to a database.
/// </remarks>
public sealed class PaymentDbContextFactory : IDesignTimeDbContextFactory<PaymentDbContext>
{
    public PaymentDbContext CreateDbContext(string[] args)
    {
        var options = new DbContextOptionsBuilder<PaymentDbContext>()
            .UseSqlServer("Server=(design-time);Database=PaymentDb;Trusted_Connection=True;")
            .Options;

        return new PaymentDbContext(options);
    }
}
