using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;

namespace OrderFlow.Inventory.API.Managers.DataContext;

/// <summary>
/// Builds the context for <c>dotnet ef migrations</c>, and for nothing else.
/// </summary>
/// <remarks>
/// The running service gets its connection string from Aspire, which is not available to the EF
/// tooling — it would try to start the whole host, fail to resolve "InventoryDb", and refuse to
/// scaffold. This factory hands EF a connection string it never opens: migrations are generated by
/// comparing the model to the previous migration, not by talking to a database. Nothing here is a
/// hard-coded credential, and nothing here runs at runtime.
/// </remarks>
public sealed class InventoryDbContextFactory : IDesignTimeDbContextFactory<InventoryDbContext>
{
    public InventoryDbContext CreateDbContext(string[] args)
    {
        var options = new DbContextOptionsBuilder<InventoryDbContext>()
            .UseSqlServer("Server=(design-time);Database=InventoryDb;Trusted_Connection=True;")
            .Options;

        return new InventoryDbContext(options);
    }
}
