// Bridges Aspire's environment variables into the browser.
//
// Aspire hands ORDER_API_URL and friends to the *npm process*. The code that needs them runs in the
// *browser*, which has no environment. Nothing in Angular closes that gap on its own: `environment.ts`
// is baked in at build time, so a value read from process.env there would freeze whatever port Aspire
// happened to assign on the build that produced the bundle — and Aspire assigns a different one next run.
//
// So the URLs cross the boundary as a file. This writes public/config.js, which index.html loads before
// the app boots. Consequences worth knowing:
//   - Repointing the app at different APIs needs no rebuild — rewrite this file and reload.
//   - The same mechanism works under nginx (see docker-entrypoint.sh), so the container is configurable
//     at run time rather than baked at image-build time.
//   - config.js is generated, never committed (.gitignore). postinstall writes the defaults so a bare
//     `ng serve` still gets a file rather than a 404.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

// Empty is a deliberate default, not an oversight. There is no sensible localhost fallback: Aspire
// assigns these ports dynamically, so a guess would be wrong in a way that looks like a network error.
// Empty means "not configured", and the app says exactly that instead of failing mysteriously.
const config = {
  orderApi: process.env['ORDER_API_URL'] ?? '',
  inventoryApi: process.env['INVENTORY_API_URL'] ?? '',
  paymentApi: process.env['PAYMENT_API_URL'] ?? '',
  fulfillmentApi: process.env['FULFILLMENT_API_URL'] ?? '',
};

const contents = `// GENERATED by scripts/write-config.mjs. Do not edit, do not commit.
window.__ORDERFLOW__ = ${JSON.stringify(config, null, 2)};
`;

mkdirSync(join(root, 'public'), { recursive: true });
writeFileSync(join(root, 'public', 'config.js'), contents, 'utf8');

const resolved = Object.entries(config).filter(([, url]) => url.length > 0);
console.log(
  resolved.length > 0
    ? `[orderflow] config.js written: ${resolved.map(([k, v]) => `${k}=${v}`).join(' ')}`
    : '[orderflow] config.js written with no API URLs — start via the Aspire AppHost to populate them.',
);
